spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cjafet/spring-config.git
          repos:
            development:
              pattern: 'nosqljs/dev'
              cloneOnStart: true
              uri: https://github.com/cjafet/spring-config
              searchPaths: configs/nosqljs/dev

logging:
  level:
    web: DEBUG

